[workspace]
resolver = "2"
members = [
    "simplemotion-sys",
    "simplemotion",
]

[patch.crates-io]
linuxcnc-hal-sys = { path = "../linuxcnc-hal-rs/linuxcnc-hal-sys" }
linuxcnc-hal = { path = "../linuxcnc-hal-rs/linuxcnc-hal" }
rtapi-logger = { path = "../linuxcnc-hal-rs/rtapi-logger" }
